# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dlinano/my-recognition-python

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dlinano/my-recognition-python

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dlinano/my-recognition-python/CMakeFiles /home/dlinano/my-recognition-python/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dlinano/my-recognition-python/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my-recognition

# Build rule for target.
my-recognition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my-recognition
.PHONY : my-recognition

# fast build rule for target.
my-recognition/fast:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/build
.PHONY : my-recognition/fast

#=============================================================================
# Target rules for targets named detectnet-camera

# Build rule for target.
detectnet-camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 detectnet-camera
.PHONY : detectnet-camera

# fast build rule for target.
detectnet-camera/fast:
	$(MAKE) -f CMakeFiles/detectnet-camera.dir/build.make CMakeFiles/detectnet-camera.dir/build
.PHONY : detectnet-camera/fast

detectnet-camera.o: detectnet-camera.cpp.o

.PHONY : detectnet-camera.o

# target to build an object file
detectnet-camera.cpp.o:
	$(MAKE) -f CMakeFiles/detectnet-camera.dir/build.make CMakeFiles/detectnet-camera.dir/detectnet-camera.cpp.o
.PHONY : detectnet-camera.cpp.o

detectnet-camera.i: detectnet-camera.cpp.i

.PHONY : detectnet-camera.i

# target to preprocess a source file
detectnet-camera.cpp.i:
	$(MAKE) -f CMakeFiles/detectnet-camera.dir/build.make CMakeFiles/detectnet-camera.dir/detectnet-camera.cpp.i
.PHONY : detectnet-camera.cpp.i

detectnet-camera.s: detectnet-camera.cpp.s

.PHONY : detectnet-camera.s

# target to generate assembly for a file
detectnet-camera.cpp.s:
	$(MAKE) -f CMakeFiles/detectnet-camera.dir/build.make CMakeFiles/detectnet-camera.dir/detectnet-camera.cpp.s
.PHONY : detectnet-camera.cpp.s

my-recognition.o: my-recognition.cpp.o

.PHONY : my-recognition.o

# target to build an object file
my-recognition.cpp.o:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/my-recognition.cpp.o
.PHONY : my-recognition.cpp.o

my-recognition.i: my-recognition.cpp.i

.PHONY : my-recognition.i

# target to preprocess a source file
my-recognition.cpp.i:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/my-recognition.cpp.i
.PHONY : my-recognition.cpp.i

my-recognition.s: my-recognition.cpp.s

.PHONY : my-recognition.s

# target to generate assembly for a file
my-recognition.cpp.s:
	$(MAKE) -f CMakeFiles/my-recognition.dir/build.make CMakeFiles/my-recognition.dir/my-recognition.cpp.s
.PHONY : my-recognition.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... my-recognition"
	@echo "... detectnet-camera"
	@echo "... detectnet-camera.o"
	@echo "... detectnet-camera.i"
	@echo "... detectnet-camera.s"
	@echo "... my-recognition.o"
	@echo "... my-recognition.i"
	@echo "... my-recognition.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

